---
title: Miraj Patel
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: miraj@madebymiraj.com
description: 'Miraj Patel is a designer based in the Greater NYC Area with a passion
  for designing beautiful and functional interfaces. He specializes in the areas of
  User Experience, Visual Design, and Front-End Development.

'
baseurl: ''
url: ''
linkedin_username: madebymiraj
twitter_username: madebymiraj
instagram_username: madebymiraj
github_username: madebymiraj
markdown: kramdown
